export const pathNames = {
  HOME: "/",
  LOGIN: "/login",
  ATTENDANCE: "/attendance",
  FACULTY: "/faculty",
  LETTER: "/letter",
  NOTIFICATION: "/notification",
  ROOM: "/room",
  SUBJECT: "/subject",
  USER: "/user",
  CLASS: "/class",
  THEME: "/theme",
  PERMISSION: "/permission",
  STUDENT: "/student",
};
